# Generated by Django 5.2.6 on 2025-09-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=255)),
                ('city', models.CharField(max_length=70)),
                ('roll_number', models.IntegerField()),
            ],
        ),
    ]
